// PRODUCTOS de inventario
// Ejecutar:  mongosh < 03_productos.js

const dbName = 'nutricion_hogar_bambi';
const dbConn = db.getSiblingDB(dbName);

dbConn.productos.deleteMany({});

dbConn.productos.insertMany([
  // --- CARNES ---
  {
    _id: 'BISTEC',
    nombre: 'Bistec',
    categoria: 'Carnes',
    unidad: 'kg',
    stockMinBambiEnlace: 32,
    stockMinBambiII: 7,
    stockMinBambiIII: 18,
    stockMinBambiIV: 7,
    stockMinBambiV: 8,
  },
  {
    _id: 'FALDA',
    nombre: 'Falda',
    categoria: 'Carnes',
    unidad: 'kg',
    stockMinBambiEnlace: 38,
    stockMinBambiII: 10,
    stockMinBambiIII: 6,
    stockMinBambiIV: 10,
    stockMinBambiV: 15,
  },
  {
    _id: 'GUISAR',
    nombre: 'Guisar',
    categoria: 'Carnes',
    unidad: 'kg',
    stockMinBambiEnlace: 26,
    stockMinBambiII: 6,
    stockMinBambiIII: 10,
    stockMinBambiIV: 6,
    stockMinBambiV: 8,
  },
  {
    _id: 'MOLIDA',
    nombre: 'Molida',
    categoria: 'Carnes',
    unidad: 'kg',
    stockMinBambiEnlace: 59,
    stockMinBambiII: 15,
    stockMinBambiIII: 20,
    stockMinBambiIV: 14,
    stockMinBambiV: 19,
  },
  // --- FRUTAS Y HORTALIZAS ---
  {
    _id: 'AJO_PORRO',
    nombre: 'Ajo Porro',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 10.5,
    stockMinBambiII: 3.5,
    stockMinBambiIII: 2.25,
    stockMinBambiIV: 3.5,
    stockMinBambiV: 3.4,
  },
  {
    _id: 'ALBAHACA',
    nombre: 'Albahaca',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 0.28,
    stockMinBambiII: 0.08,
    stockMinBambiIII: 0.14,
    stockMinBambiIV: 0.08,
    stockMinBambiV: 0.06,
  },
  {
    _id: 'APIO',
    nombre: 'Apio',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 14,
    stockMinBambiII: 4,
    stockMinBambiIII: 0,
    stockMinBambiIV: 4,
    stockMinBambiV: 7,
  },
  {
    _id: 'AUYAMA',
    nombre: 'Auyama',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 22.5,
    stockMinBambiII: 6.5,
    stockMinBambiIII: 0,
    stockMinBambiIV: 6.5,
    stockMinBambiV: 8,
  },
  {
    _id: 'BROCOLI',
    nombre: 'Brocoli',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 12,
    stockMinBambiII: 3,
    stockMinBambiIII: 4,
    stockMinBambiIV: 3,
    stockMinBambiV: 3.4,
  },
  {
    _id: 'CALABACIN',
    nombre: 'Calabacin',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 27.5,
    stockMinBambiII: 6,
    stockMinBambiIII: 5,
    stockMinBambiIV: 7,
    stockMinBambiV: 9,
  },
  {
    _id: 'CAMBUR',
    nombre: 'Cambur',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 29,
    stockMinBambiII: 10,
    stockMinBambiIII: 0,
    stockMinBambiIV: 10,
    stockMinBambiV: 24,
  },
  {
    _id: 'CEBOLLA',
    nombre: 'Cebolla',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 39,
    stockMinBambiII: 9,
    stockMinBambiIII: 10,
    stockMinBambiIV: 9,
    stockMinBambiV: 11,
  },
  {
    _id: 'CEBOLLIN',
    nombre: 'Cebollin',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 9,
    stockMinBambiII: 3.5,
    stockMinBambiIII: 2.5,
    stockMinBambiIV: 3.5,
    stockMinBambiV: 3.2,
  },
  {
    _id: 'CELERI',
    nombre: 'Celeri',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 9,
    stockMinBambiII: 3.5,
    stockMinBambiIII: 2.5,
    stockMinBambiIV: 3.5,
    stockMinBambiV: 3.2,
  },
  {
    _id: 'CHAYOTA',
    nombre: 'Chayota',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 14.5,
    stockMinBambiII: 3.5,
    stockMinBambiIII: 2.6,
    stockMinBambiIV: 3.5,
    stockMinBambiV: 4.7,
  },
  {
    _id: 'CILANTRO',
    nombre: 'Cilantro',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 10.2,
    stockMinBambiII: 2.5,
    stockMinBambiIII: 2.6,
    stockMinBambiIV: 2.5,
    stockMinBambiV: 3.2,
  },
  {
    _id: 'ESPINACA',
    nombre: 'Espinaca',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 8,
    stockMinBambiII: 2.4,
    stockMinBambiIII: 0,
    stockMinBambiIV: 2.4,
    stockMinBambiV: 2.7,
  },
  {
    _id: 'GUAYABA',
    nombre: 'Guayaba',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 9,
    stockMinBambiII: 2,
    stockMinBambiIII: 0,
    stockMinBambiIV: 2,
    stockMinBambiV: 3,
  },
  {
    _id: 'LECHOZA',
    nombre: 'Lechoza',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 80,
    stockMinBambiII: 26,
    stockMinBambiIII: 0,
    stockMinBambiIV: 25.5,
    stockMinBambiV: 36.5,
  },
  {
    _id: 'LECHUGA',
    nombre: 'Lechuga',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 4.7,
    stockMinBambiII: 1.6,
    stockMinBambiIII: 1.8,
    stockMinBambiIV: 1.6,
    stockMinBambiV: 1.1,
  },
  {
    _id: 'MELON',
    nombre: 'Melon',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 67,
    stockMinBambiII: 21,
    stockMinBambiIII: 0,
    stockMinBambiIV: 21,
    stockMinBambiV: 31,
  },
  {
    _id: 'NARANJA',
    nombre: 'Naranja',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 4,
    stockMinBambiII: 1,
    stockMinBambiIII: 3,
    stockMinBambiIV: 1,
    stockMinBambiV: 0.6,
  },
  {
    _id: 'OCUMO',
    nombre: 'Ocumo',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 4,
    stockMinBambiII: 1,
    stockMinBambiIII: 0,
    stockMinBambiIV: 2,
    stockMinBambiV: 2,
  },
  {
    _id: 'PAPAS',
    nombre: 'Papas',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 146,
    stockMinBambiII: 33,
    stockMinBambiIII: 46,
    stockMinBambiIV: 33,
    stockMinBambiV: 42,
  },
  {
    _id: 'PATILLA',
    nombre: 'Patilla',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 135,
    stockMinBambiII: 40,
    stockMinBambiIII: 0,
    stockMinBambiIV: 40,
    stockMinBambiV: 62,
  },
  {
    _id: 'PEPINO',
    nombre: 'Pepino',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 8.2,
    stockMinBambiII: 2.5,
    stockMinBambiIII: 3,
    stockMinBambiIV: 2.5,
    stockMinBambiV: 2.2,
  },
  {
    _id: 'PIMENTON',
    nombre: 'Pimenton',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 35,
    stockMinBambiII: 8.5,
    stockMinBambiIII: 11,
    stockMinBambiIV: 8.5,
    stockMinBambiV: 9.8,
  },
  {
    _id: 'PLATANO',
    nombre: 'Platano',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 208,
    stockMinBambiII: 53,
    stockMinBambiIII: 50,
    stockMinBambiIV: 53,
    stockMinBambiV: 47,
  },
  {
    _id: 'REMOLACHA',
    nombre: 'Remolacha',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 12,
    stockMinBambiII: 2.5,
    stockMinBambiIII: 6,
    stockMinBambiIV: 2.5,
    stockMinBambiV: 2.4,
  },
  {
    _id: 'REPOLLO_BLANCO',
    nombre: 'Repollo Blanco',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 13,
    stockMinBambiII: 4.5,
    stockMinBambiIII: 6.5,
    stockMinBambiIV: 4.5,
    stockMinBambiV: 2.7,
  },
  {
    _id: 'REPOLLO_MORADO',
    nombre: 'Repollo Morado',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 2,
    stockMinBambiII: 0.7,
    stockMinBambiIII: 1,
    stockMinBambiIV: 0.8,
    stockMinBambiV: 0.45,
  },
  {
    _id: 'TOMATE',
    nombre: 'Tomate',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 43.5,
    stockMinBambiII: 10,
    stockMinBambiIII: 16.5,
    stockMinBambiIV: 10,
    stockMinBambiV: 10.3,
  },
  {
    _id: 'YUCA',
    nombre: 'Yuca',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 14,
    stockMinBambiII: 3,
    stockMinBambiIII: 7,
    stockMinBambiIV: 3,
    stockMinBambiV: 3,
  },
  {
    _id: 'ZANAHORIA',
    nombre: 'Zanahoria',
    categoria: 'Frutas y Hortalizas',
    unidad: 'kg',
    stockMinBambiEnlace: 46,
    stockMinBambiII: 12,
    stockMinBambiIII: 11.5,
    stockMinBambiIV: 12,
    stockMinBambiV: 15,
  },
  // --- HUEVOS ---
  {
    _id: 'HUEVOS',
    nombre: 'Huevos',
    categoria: 'Huevos',
    unidad: 'u',
    stockMinBambiEnlace: 1183,
    stockMinBambiII: 333,
    stockMinBambiIII: 36,
    stockMinBambiIV: 333,
    stockMinBambiV: 422,
  },
  // --- PLUMROSE ---
  {
    _id: 'JAMON',
    nombre: 'Jamon',
    categoria: 'Plumrose',
    unidad: 'kg',
    stockMinBambiEnlace: 20,
    stockMinBambiII: 7,
    stockMinBambiIII: 2,
    stockMinBambiIV: 7,
    stockMinBambiV: 0,
  },
  {
    _id: 'SALCHICHAS',
    nombre: 'Salchichas',
    categoria: 'Plumrose',
    unidad: 'u',
    stockMinBambiEnlace: 465,
    stockMinBambiII: 120,
    stockMinBambiIII: 158,
    stockMinBambiIV: 120,
    stockMinBambiV: 0,
  },
  // --- POLLO ---
  {
    _id: 'PECHUGA',
    nombre: 'Pechuga',
    categoria: 'Pollo',
    unidad: 'kg',
    stockMinBambiEnlace: 5,
    stockMinBambiII: 1,
    stockMinBambiIII: 2,
    stockMinBambiIV: 1,
    stockMinBambiV: 0.7,
  },
  {
    _id: 'POLLO',
    nombre: 'Pollo',
    categoria: 'Pollo',
    unidad: 'kg',
    stockMinBambiEnlace: 140,
    stockMinBambiII: 28,
    stockMinBambiIII: 36,
    stockMinBambiIV: 28,
    stockMinBambiV: 39,
  },
  // --- QUESO ---
  {
    _id: 'QUESO',
    nombre: 'Queso',
    categoria: 'Queso',
    unidad: 'kg',
    stockMinBambiEnlace: 59,
    stockMinBambiII: 18,
    stockMinBambiIII: 1.5,
    stockMinBambiIV: 18,
    stockMinBambiV: 15,
  },
  // --- VIVERES ---
  {
    _id: 'ACEITE',
    nombre: 'Aceite',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 29,
    stockMinBambiII: 9,
    stockMinBambiIII: 5,
    stockMinBambiIV: 9,
    stockMinBambiV: 11,
  },
  {
    _id: 'ARROZ',
    nombre: 'Arroz',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 44,
    stockMinBambiII: 11,
    stockMinBambiIII: 22,
    stockMinBambiIV: 11,
    stockMinBambiV: 10,
  },
  {
    _id: 'AZUCAR',
    nombre: 'Azucar',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 26,
    stockMinBambiII: 8,
    stockMinBambiIII: 4,
    stockMinBambiIV: 8,
    stockMinBambiV: 4,
  },
  {
    _id: 'CARAOTAS_NEGRAS',
    nombre: 'Caraotas Negras',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 6.5,
    stockMinBambiII: 3,
    stockMinBambiIII: 2,
    stockMinBambiIV: 3,
    stockMinBambiV: 2.5,
  },
  {
    _id: 'CARAOTAS_ROJAS',
    nombre: 'Caraotas Rojas',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 2.7,
    stockMinBambiII: 1,
    stockMinBambiIII: 0,
    stockMinBambiIV: 1,
    stockMinBambiV: 1,
  },
  {
    _id: 'CEREAL_1',
    nombre: 'Cereal 1',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 11.3,
    stockMinBambiII: 5,
    stockMinBambiIII: 0,
    stockMinBambiIV: 5,
    stockMinBambiV: 5.7,
  },
  {
    _id: 'CEREAL_2',
    nombre: 'Cereal 2',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 0,
    stockMinBambiII: 0,
    stockMinBambiIII: 0,
    stockMinBambiIV: 0,
    stockMinBambiV: 0,
  },
  {
    _id: 'CERELAC',
    nombre: 'Cerelac',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 2,
    stockMinBambiII: 2,
    stockMinBambiIII: 0,
    stockMinBambiIV: 2,
    stockMinBambiV: 4,
  },
  {
    _id: 'COMPOTAS',
    nombre: 'Compotas',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 0,
    stockMinBambiII: 0,
    stockMinBambiIII: 0,
    stockMinBambiIV: 0,
    stockMinBambiV: 154,
  },
  {
    _id: 'COTUFA',
    nombre: 'Cotufas',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 2.5,
    stockMinBambiII: 1,
    stockMinBambiIII: 0,
    stockMinBambiIV: 1,
    stockMinBambiV: 0,
  },
  {
    _id: 'CREMA_ARROZ',
    nombre: 'Crema de Arroz',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 7,
    stockMinBambiII: 4,
    stockMinBambiIII: 0,
    stockMinBambiIV: 4,
    stockMinBambiV: 4,
  },
  {
    _id: 'CREMA_LECHE',
    nombre: 'Crema de Leche',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 2,
    stockMinBambiII: 1,
    stockMinBambiIII: 0,
    stockMinBambiIV: 1,
    stockMinBambiV: 1,
  },
  {
    _id: 'FIDEO',
    nombre: 'Fideo',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 3,
    stockMinBambiII: 2,
    stockMinBambiIII: 0.5,
    stockMinBambiIV: 2,
    stockMinBambiV: 1.2,
  },
  {
    _id: 'FORORO',
    nombre: 'Fororo',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 6,
    stockMinBambiII: 4,
    stockMinBambiIII: 0,
    stockMinBambiIV: 4,
    stockMinBambiV: 3.3,
  },
  {
    _id: 'GALLETA_DULCE',
    nombre: 'Galleta Dulce',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 410,
    stockMinBambiII: 120,
    stockMinBambiIII: 0,
    stockMinBambiIV: 120,
    stockMinBambiV: 14,
  },
  {
    _id: 'GALLETA_SALADA',
    nombre: 'Galleta salada',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 410,
    stockMinBambiII: 120,
    stockMinBambiIII: 0,
    stockMinBambiIV: 120,
    stockMinBambiV: 0,
  },
  {
    _id: 'GELATINA',
    nombre: 'Gelatina',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 5,
    stockMinBambiII: 4,
    stockMinBambiIII: 0,
    stockMinBambiIV: 4,
    stockMinBambiV: 4,
  },
  {
    _id: 'HARINA_AVENA',
    nombre: 'Harina de Avena',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 16,
    stockMinBambiII: 6,
    stockMinBambiIII: 0,
    stockMinBambiIV: 6,
    stockMinBambiV: 10,
  },
  {
    _id: 'HARINA_MAIZ',
    nombre: 'Harina de Maiz',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 152,
    stockMinBambiII: 45,
    stockMinBambiIII: 2,
    stockMinBambiIV: 45,
    stockMinBambiV: 51,
  },
  {
    _id: 'HARINA_TRIGO',
    nombre: 'Harina de Trigo',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 13,
    stockMinBambiII: 4,
    stockMinBambiIII: 1,
    stockMinBambiIV: 4,
    stockMinBambiV: 5,
  },
  {
    _id: 'LECHE',
    nombre: 'Leche',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 48,
    stockMinBambiII: 15.5,
    stockMinBambiIII: 1,
    stockMinBambiIV: 15.5,
    stockMinBambiV: 27,
  },
  {
    _id: 'LENTEJAS',
    nombre: 'Lentejas',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 1,
    stockMinBambiII: 1,
    stockMinBambiIII: 0,
    stockMinBambiIV: 1,
    stockMinBambiV: 0.5,
  },
  {
    _id: 'MAIZENA',
    nombre: 'Maizena',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 0.4,
    stockMinBambiII: 0.2,
    stockMinBambiIII: 0.2,
    stockMinBambiIV: 0.2,
    stockMinBambiV: 1.1,
  },
  {
    _id: 'MARGARINA',
    nombre: 'Margarina',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 26,
    stockMinBambiII: 9,
    stockMinBambiIII: 3,
    stockMinBambiIV: 9,
    stockMinBambiV: 9,
  },
  {
    _id: 'MARIA',
    nombre: 'Maria',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 0,
    stockMinBambiII: 0,
    stockMinBambiIII: 0,
    stockMinBambiIV: 0,
    stockMinBambiV: 28,
  },
  {
    _id: 'MAYONESA',
    nombre: 'Mayonesa',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 4,
    stockMinBambiII: 3.5,
    stockMinBambiIII: 4,
    stockMinBambiIV: 3.5,
    stockMinBambiV: 3.2,
  },
  {
    _id: 'MERMELADA',
    nombre: 'Mermelada',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 6,
    stockMinBambiII: 2.7,
    stockMinBambiIII: 0,
    stockMinBambiIV: 2.2,
    stockMinBambiV: 0,
  },
  {
    _id: 'MEZCLA_CACHAPA',
    nombre: 'Mezcla de Cachapa',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 4,
    stockMinBambiII: 2,
    stockMinBambiIII: 0,
    stockMinBambiIV: 2,
    stockMinBambiV: 3,
  },
  {
    _id: 'NESTUM',
    nombre: 'Nestum',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 1,
    stockMinBambiII: 1,
    stockMinBambiIII: 0,
    stockMinBambiIV: 1,
    stockMinBambiV: 4,
  },
  {
    _id: 'PASTA',
    nombre: 'Pasta',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 26,
    stockMinBambiII: 7,
    stockMinBambiIII: 16,
    stockMinBambiIV: 7,
    stockMinBambiV: 7,
  },
  {
    _id: 'PASTA_TOMATE',
    nombre: 'Pasta de Tomate',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 1,
    stockMinBambiII: 0.5,
    stockMinBambiIII: 0.5,
    stockMinBambiIV: 0.5,
    stockMinBambiV: 0,
  },
  {
    _id: 'ROMERO',
    nombre: 'Romero',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 0.1,
    stockMinBambiII: 0.1,
    stockMinBambiIII: 0.1,
    stockMinBambiIV: 0.1,
    stockMinBambiV: 0.1,
  },
  {
    _id: 'SALSA_SOYA',
    nombre: 'Salsa de Soya',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 0.5,
    stockMinBambiII: 0.1,
    stockMinBambiIII: 0.2,
    stockMinBambiIV: 0.1,
    stockMinBambiV: 0.1,
  },
  {
    _id: 'VAINILLA',
    nombre: 'Vainilla',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 0.4,
    stockMinBambiII: 0.4,
    stockMinBambiIII: 0,
    stockMinBambiIV: 0.4,
    stockMinBambiV: 0.4,
  },
  {
    _id: 'VINAGRE',
    nombre: 'Vinagre',
    categoria: 'Viveres',
    unidad: 'u',
    stockMinBambiEnlace: 3.5,
    stockMinBambiII: 1.2,
    stockMinBambiIII: 1.3,
    stockMinBambiIV: 1.2,
    stockMinBambiV: 1.3,
  },
  {
    _id: 'CARAOTAS_BLANCAS',
    nombre: 'Caraotas blancas',
    categoria: 'Viveres',
    unidad: 'kg',
    stockMinBambiEnlace: 1,
    stockMinBambiII: 0.5,
    stockMinBambiIII: 0,
    stockMinBambiIV: 0.5,
    stockMinBambiV: 0.5,
  }
]);

// Índices útiles para búsquedas por nombre
dbConn.productos.createIndex({ nombre: 1 }, { unique: true });

print('Productos insertados en DB ' + dbName);